services:
  mysql:
    image: mysql:8.0
    container_name: franchise-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: franchise_db
    ports:
      - "3307:3306"
    volumes:
      - ../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: franchise-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: